#!/usr/bin/env zsh
# ralph.sh — Automated Claude Code builder
# Executes tasks from PRD.md one at a time in headless mode.
# Runs sanity checks between phases. Self-heals on build failures (max 3 attempts).
# Commits once per phase. Tracks findings in FINDINGS.md.

set -euo pipefail

# ── Trap Ctrl+C to exit cleanly ──────────────────────────
cleanup() {
  echo ""
  echo -e "\033[0;31m[$(date '+%Y-%m-%d %H:%M:%S')] Ralph interrupted. Exiting.\033[0m"
  kill 0 2>/dev/null
  exit 130
}
trap cleanup SIGINT SIGTERM

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
PRD_FILE="$PROJECT_DIR/PRD.md"
FINDINGS_FILE="$PROJECT_DIR/FINDINGS.md"
LOG_FILE="$PROJECT_DIR/ralph.log"
MAX_FIX_ATTEMPTS=3

# ── Colors ────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# ══════════════════════════════════════════════════════════
#  CUSTOMIZE: Task list — format: "task_id|phase|description"
#  Must match PRD.md checkboxes exactly.
# ══════════════════════════════════════════════════════════
TASKS=(
  # "1.1|1|First task"
  # "1.2|1|Second task"
  # "2.1|2|Third task"
)

# ══════════════════════════════════════════════════════════
#  CUSTOMIZE: Phase names (for commit messages and logging)
# ══════════════════════════════════════════════════════════
get_phase_name() {
  case "$1" in
    1) echo "Phase 1 Name" ;;
    2) echo "Phase 2 Name" ;;
    # Add more phases...
  esac
}

# ── Helpers ───────────────────────────────────────────────
timestamp() { date "+%Y-%m-%d %H:%M:%S" }

log() {
  echo -e "${CYAN}[$(timestamp)]${NC} $1" | tee -a "$LOG_FILE"
}

log_success() {
  echo -e "${GREEN}[$(timestamp)] ✓${NC} $1" | tee -a "$LOG_FILE"
}

log_error() {
  echo -e "${RED}[$(timestamp)] ✗${NC} $1" | tee -a "$LOG_FILE"
}

log_phase() {
  echo "" | tee -a "$LOG_FILE"
  echo -e "${BOLD}${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | tee -a "$LOG_FILE"
  echo -e "${BOLD}${BLUE}  Phase $1${NC}" | tee -a "$LOG_FILE"
  echo -e "${BOLD}${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | tee -a "$LOG_FILE"
}

# Check if a task is already marked done in PRD.md
is_task_done() {
  local task_id="$1"
  grep -q "\[x\] \*\*${task_id}\*\*" "$PRD_FILE" 2>/dev/null
}

# Mark a task as done in PRD.md ([ ] → [x])
# NOTE: macOS sed syntax. On Linux, change `sed -i ''` to `sed -i`
mark_task_done() {
  local task_id="$1"
  sed -i '' "s/- \[ \] \*\*${task_id}\*\*/- [x] **${task_id}**/" "$PRD_FILE"
}

# ── Init findings file ────────────────────────────────────
init_findings() {
  if [[ ! -f "$FINDINGS_FILE" ]]; then
    cat > "$FINDINGS_FILE" << 'EOF'
# Findings & Decisions Log

Auto-generated by ralph. Each task logs its decisions and findings here.

---

EOF
    log "Created FINDINGS.md"
  fi
}

# ══════════════════════════════════════════════════════════
#  OPTIONAL: UI task handling
#  If your project has frontend/UI work, list UI task IDs
#  here to inject /frontend-design skill instructions.
#  Delete this section if not needed.
# ══════════════════════════════════════════════════════════
# UI_TASKS=("3.2" "4.1" "5.1")
#
# is_ui_task() {
#   local task_id="$1"
#   for ui_id in "${UI_TASKS[@]}"; do
#     [[ "$task_id" == "$ui_id" ]] && return 0
#   done
#   return 1
# }

# ══════════════════════════════════════════════════════════
#  CUSTOMIZE: The prompt template
#  Edit the RULES section for your project's constraints.
# ══════════════════════════════════════════════════════════
run_task() {
  local task_id="$1"
  local description="$2"

  # Uncomment if using UI_TASKS:
  # local ui_instruction=""
  # if is_ui_task "$task_id"; then
  #   ui_instruction="
  # - IMPORTANT: Use the /frontend-design skill for this task."
  # fi

  local prompt="You are implementing a software project.

PROJECT DIRECTORY: $PROJECT_DIR

YOUR TASK: Execute task **${task_id}** — \"${description}\"

Read the full task specification from PRD.md (task ${task_id}) and implement it exactly.
Read FINDINGS.md to understand any decisions or context from previous tasks.

RULES:
- Only do what this specific task requires. Do not touch other tasks.
- After completing the task, append your findings/decisions to FINDINGS.md under a heading '## Task ${task_id}: ${description}'.
  Include: what you did, any decisions you made, any issues encountered, and any notes for future tasks. Keep it concise (3-8 bullet points).
- Do NOT commit anything to git.
- Do NOT run the dev server or any long-running processes.
- If a task says to install packages, actually run the install command.
- If a task says to create a file, create the file with the full implementation.
- Make sure all types and imports are correct."

  log "  Running Claude for task ${task_id}..."

  # ════════════════════════════════════════════════════════
  #  CUSTOMIZE: --model and --allowedTools
  #  Baseline tools: Bash,Read,Write,Edit,Glob,Grep
  #  Add Skill if using skills (e.g., /frontend-design)
  #  Add MCP tools by name if needed
  # ════════════════════════════════════════════════════════
  claude -p "$prompt" \
    --model sonnet \
    --allowedTools "Bash,Read,Write,Edit,Glob,Grep" \
    >> "$LOG_FILE" 2>&1 || true

  log_success "  Task ${task_id} completed"
}

# ══════════════════════════════════════════════════════════
#  CUSTOMIZE: Sanity checks for your stack
#  What does "healthy build" mean for your project?
#  Common patterns:
#    TypeScript: tsc --noEmit, eslint, vite build / next build
#    Python:     ruff check ., mypy src/, pytest
#    Go:         go vet ./..., go build ./..., go test ./...
#    Rust:       cargo check, cargo clippy, cargo test
# ══════════════════════════════════════════════════════════
run_sanity_checks() {
  local phase="$1"
  log "  Running sanity checks for Phase ${phase}..."

  local check_output=""
  local exit_code=0

  # Example: TypeScript typecheck
  # log "    Running tsc..."
  # check_output=$(cd "$PROJECT_DIR" && npx tsc --noEmit 2>&1) || exit_code=$?
  # if [[ $exit_code -ne 0 ]]; then
  #   log_error "    TypeScript check failed"
  #   echo "$check_output" >> "$LOG_FILE"
  #   echo "$check_output"
  #   return 1
  # fi
  # log_success "    TypeScript OK"

  # Example: Build
  # log "    Running build..."
  # check_output=$(cd "$PROJECT_DIR" && npm run build 2>&1) || exit_code=$?
  # if [[ $exit_code -ne 0 ]]; then
  #   log_error "    Build failed"
  #   echo "$check_output" >> "$LOG_FILE"
  #   echo "$check_output"
  #   return 1
  # fi
  # log_success "    Build OK"

  # Example: Phase-conditional tests (only after tests exist)
  # if [[ $phase -ge 3 ]]; then
  #   log "    Running tests..."
  #   check_output=$(cd "$PROJECT_DIR" && npm test 2>&1) || exit_code=$?
  #   if [[ $exit_code -ne 0 ]]; then
  #     log_error "    Tests failed"
  #     echo "$check_output" >> "$LOG_FILE"
  #     echo "$check_output"
  #     return 1
  #   fi
  #   log_success "    Tests OK"
  # fi

  log_success "  All sanity checks passed for Phase ${phase}"
  return 0
}

# ── Fix build errors via Claude ───────────────────────────
fix_build() {
  local phase="$1"
  local error_output="$2"
  local attempt="$3"

  log "  Fix attempt ${attempt}/${MAX_FIX_ATTEMPTS}..."

  local prompt="You are implementing a software project.

PROJECT DIRECTORY: $PROJECT_DIR

The build/validation failed after completing Phase ${phase}. Fix the errors below.

ERROR OUTPUT:
\`\`\`
${error_output}
\`\`\`

RULES:
- Read the relevant files to understand the context before fixing.
- Only fix what's broken. Do not refactor or change unrelated code.
- Read PRD.md if you need to understand the intended design.
- After fixing, append a brief note to FINDINGS.md under '## Phase ${phase} — Build Fix (attempt ${attempt})' describing what went wrong and how you fixed it.
- Do NOT commit anything to git.
- Do NOT run the dev server."

  claude -p "$prompt" \
    --model sonnet \
    --allowedTools "Bash,Read,Write,Edit,Glob,Grep" \
    >> "$LOG_FILE" 2>&1 || true
}

# ── Commit a phase ────────────────────────────────────────
commit_phase() {
  local phase="$1"
  local phase_name="$2"

  log "  Committing Phase ${phase}..."
  cd "$PROJECT_DIR"
  git add -A
  git commit -m "$(cat <<EOF
phase ${phase}: ${phase_name}

Automated by ralph.sh
EOF
)" 2>&1 | tee -a "$LOG_FILE"
  log_success "  Phase ${phase} committed"
}

# ── Main loop ─────────────────────────────────────────────
main() {
  echo "" > "$LOG_FILE"
  log "${BOLD}Ralph — automated builder${NC}"
  log "Project: $PROJECT_DIR"
  log ""

  init_findings

  local current_phase=0

  for task_entry in "${TASKS[@]}"; do
    local task_id="${task_entry%%|*}"
    local remainder="${task_entry#*|}"
    local phase="${remainder%%|*}"
    local description="${remainder#*|}"

    # ── Phase boundary: sanity check + commit previous phase ──
    if [[ $phase -ne $current_phase ]]; then
      if [[ $current_phase -ne 0 ]]; then
        local error_output check_result
        error_output=$(run_sanity_checks "$current_phase" 2>&1) && check_result=0 || check_result=$?

        if [[ $check_result -ne 0 ]]; then
          local fixed=false
          for attempt in $(seq 1 $MAX_FIX_ATTEMPTS); do
            fix_build "$current_phase" "$error_output" "$attempt"
            error_output=$(run_sanity_checks "$current_phase" 2>&1) && check_result=0 || check_result=$?
            if [[ $check_result -eq 0 ]]; then
              fixed=true
              log_success "  Build fixed on attempt ${attempt}"
              break
            fi
          done

          if [[ "$fixed" != "true" ]]; then
            log_error "  Phase ${current_phase} could not be fixed after ${MAX_FIX_ATTEMPTS} attempts."
            log_error "  Halting. Check ralph.log for details."
            exit 1
          fi
        fi

        commit_phase "$current_phase" "$(get_phase_name $current_phase)"
      fi

      current_phase=$phase
      log_phase "$phase — $(get_phase_name $phase)"
    fi

    # ── Skip completed tasks ──
    if is_task_done "$task_id"; then
      log "  Skipping ${task_id} (already done)"
      continue
    fi

    # ── Execute task ──
    log "${YELLOW}► Task ${task_id}: ${description}${NC}"
    run_task "$task_id" "$description"
    mark_task_done "$task_id"
  done

  # ── Final phase: sanity check + commit ──
  if [[ $current_phase -ne 0 ]]; then
    local error_output check_result
    error_output=$(run_sanity_checks "$current_phase" 2>&1) && check_result=0 || check_result=$?

    if [[ $check_result -ne 0 ]]; then
      local fixed=false
      for attempt in $(seq 1 $MAX_FIX_ATTEMPTS); do
        fix_build "$current_phase" "$error_output" "$attempt"
        error_output=$(run_sanity_checks "$current_phase" 2>&1) && check_result=0 || check_result=$?
        if [[ $check_result -eq 0 ]]; then
          fixed=true
          log_success "  Build fixed on attempt ${attempt}"
          break
        fi
      done

      if [[ "$fixed" != "true" ]]; then
        log_error "  Final phase could not be fixed after ${MAX_FIX_ATTEMPTS} attempts."
        log_error "  Halting. Check ralph.log for details."
        exit 1
      fi
    fi

    commit_phase "$current_phase" "$(get_phase_name $current_phase)"
  fi

  echo ""
  log_success "${BOLD}Ralph complete! All phases built and committed.${NC}"
  log "Check FINDINGS.md for decisions log."
  log "Check ralph.log for full output."
}

main "$@"
